### ISSUE TITLE
Parse keys case-insensitively if specified

### ISSUE THREAD

**Issue by parhamdoustdar** [ericaro/frontmatter#1]
First off, thanks for the awesome helpful library. I used it in my command line tool called [godium][], and that tool will help me a lot in the coming years.

However, one thing one of the users asked for is the case-insensitive parsing of front matter keys. For example, if I have a struct like this:

```
struct PostData {
    Title string `fm:"title"`
}
```

And if I try and unmarshal a front matter like this:

```
---
Title: Some title!
---
```

It should be assigned to the `Title` property of the struct.

Is this possible? I looked at the `yaml` library, but couldn't find a way of parsing yaml content case-insensitively.

[godium]: https://github.com/parhamdoustdar/godium

**Comment by ericaro** [comment]
This is more a go-yaml issue don't you think ?
